export const loginPage = {
    en: {
        pageName: "Account",
        title: "Log in",
        subtitle: "To access your account",
        emailLabel: "Email",
        passwordLabel: "Password",
        rememberMe: "Remember me",
        submit: "Sign in",
        noAccount: "Don't have an account?",
        create: "Create an account",
        submitting: "Logging in...",
    },
    kr: {
        pageName: "계정",
        title: "로그인",
        subtitle: "계정에 접근하기",
        emailLabel: "이메일",
        passwordLabel: "비밀번호",
        rememberMe: "기억하기",
        submit: "로그인",
        noAccount: "계정이 없으신가요?",
        create: "계정 만들기",
        submitting: "로그인 중...",
    },
};

export const signupPage = {
    en: {
        pageName: "Account",
        title: "Sign up",
        usernameLabel: "Username",
        emailLabel: "Email",
        passwordLabel: "Password",
        phoneLabel: "Phone Number",
        addressLabel: "Address",
        policyTextStart: "By creating an account, you agree to the",
        termsOfUse: "Terms of use",
        policyTextMiddle: "and",
        privacyPolicy: " Privacy Policy",
        policyTextLast: ".",
        submit: "Sign up",
        alreadyHaveAccount: "Already have an account? ",
        login: "Log in",
        submitting: "Signing up...",
    },
    kr: {
        pageName: "계정",
        title: "회원가입",
        usernameLabel: "이름",
        emailLabel: "이메일",
        passwordLabel: "비밀번호",
        phoneLabel: "전화번호",
        addressLabel: "주소",
        policyTextStart: "계정을 생성함으로써,",
        termsOfUse: "이용 약관",
        policyTextMiddle: "및 ",
        privacyPolicy: "개인정보 처리방침",
        policyTextLast: "에 동의하게 됩니다.",
        submit: "회원가입",
        alreadyHaveAccount: "이미 계정이 있으신가요? ",
        login: "로그인",
        submitting: "회원가입 중...",
    },
};
