export const chatPage = {
  ko: {
    loading: "로딩 중...",
    error: "오류가 발생했습니다.",
    loginRequired: "로그인이 필요한 서비스입니다.",
    chatPetInfo: {
      loading: "로딩 중...",
      age: "나이",
      species: "품종",
      location: "위치",
      description: "설명",
      years: "살",
    },
    chatFile: {
      loading: "데이터를 불러올 수 없습니다.",
      application: "님의 입양 신청서",
      back: "뒤로 가기",
      applicationNumber: "신청서 #",
      submissionDate: "제출일",
      homeImages: "거주 환경 사진",
      homeImage: "거주 환경",
      answers: "입양 신청 답변",
    },
    chat: {
      inputPlaceholder: "메시지를 입력하세요...",
      sending: "전송 중...",
      send: "전송",
      back: "←",
      conversationWith: "님과의 대화",
      conversationBetween: "님과 님의 대화",
      conversationWithAuthor: "게시물 작성자와의 대화",
      noApplicants: "입양 신청자가 없습니다.",
      applicantsList: "입양 신청자 목록",
    },
  },
  en: {
    loading: "Loading...",
    error: "An error occurred.",
    loginRequired: "This service requires login.",
    chatPetInfo: {
      loading: "Loading...",
      age: "Age",
      species: "Breed",
      location: "Location",
      description: "Description",
      years: "years",
    },
    chatFile: {
      loading: "Unable to load data.",
      application: "'s Adoption Application",
      back: "Go Back",
      applicationNumber: "Application #",
      submissionDate: "Submission Date",
      homeImages: "Home Environment Photos",
      homeImage: "Home Environment",
      answers: "Adoption Application Answers",
    },
    chat: {
      inputPlaceholder: "Type your message...",
      sending: "Sending...",
      send: "Send",
      back: "←",
      conversationWith: "'s Conversation",
      conversationBetween: "'s Conversation with ",
      conversationWithAuthor: "Conversation with Post Author",
      noApplicants: "No adoption applicants.",
      applicantsList: "Adoption Applicants List",
    },
  },
};
